# mysql
MYSQL :
  URL : "jdbc:mysql://daisy-kshop-cl02:3306/boslavedev?createDatabaseIfNotExist=true&autoReconnect=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul"
  USERNAME : "daisy"
  PASSWORD : "daisy!"
  CONNECTION_INIT_SIZE : "4"
  CONNECTION_MAX_TOTAL : "20"
  CONNECTION_MAX_IDLE : "20"
  CONNECTION_MIN_IDLE : "4"
  EVICTION_RUN : "4"
  EVICTION_RUN_MILLIS : "30000"

# common

# checkpoint
CHECKPOINT_DIR :
   SPARK_DIR : "/data1/spark/checkpoint"

# delimiter
DELIMITER :
  PIPE : "|"
  CTRL-^ : "\\036" # ascii 8진수
